version: "3"

services:
  funclub-stg-nginx:
    image: funclub-stg-nginx:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=stg"
      dockerfile: ./docker/nginx/Dockerfile
    container_name: funclub-stg-nginx
    restart: always
    volumes:
      - .:/var/www/html:ro
    ports:
      - "9090:80"
    depends_on:
      - funclub-stg-laravel

  funclub-stg-laravel:
    image: funclub-stg-laravel:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=stg"
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - .:/var/www/html
    container_name: funclub-stg-laravel
    expose:
      - "9000"

  funclub-stg-supervisord:
    image: funclub-stg-laravel:latest
    container_name: funclub-stg-supervisord
    restart: always
    volumes:
      - .:/var/www/html
    user: root
    command: ["/usr/bin/supervisord"]
