version: "3"

services:
  funclub-test-nginx:
    image: funclub-test-nginx:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=test"
      dockerfile: ./docker/nginx/Dockerfile
    container_name: funclub-test-nginx
    restart: always
    volumes:
      - .:/var/www/html:ro
    ports:
      - "9090:80"
    networks:
      backend:
    depends_on:
      - funclub-test-laravel

  funclub-test-laravel:
    image: funclub-test-laravel:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=test"
      dockerfile: ./Dockerfile
    container_name: funclub-test-laravel
    restart: always
    volumes:
      - .:/var/www/html
    expose:
      - "9000"
    networks:
      backend:

  funclub-test-supervisord:
    image: funclub-test-laravel:latest
    container_name: funclub-test-supervisord
    restart: always
    volumes:
      - .:/var/www/html
    user: root
    command:
      ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
    networks:
      backend:

  funclub-mysql:
    image: mysql:5.7
    container_name: funclub-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stg-funclub
    volumes:
      - funclub_mysql_data:/var/lib/mysql
    networks:
      backend:

networks:
  backend:
volumes:
  funclub_mysql_data: {}
