version: "3"

services:
  funclub-dev-nginx:
    image: funclub-dev-nginx:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
      dockerfile: ./docker/nginx/Dockerfile
    container_name: funclub-dev-nginx
    restart: always
    volumes:
      - .:/var/www/html:ro
    ports:
      - "9090:80"
    depends_on:
      - funclub-dev-laravel

  funclub-dev-laravel:
    image: funclub-dev-laravel:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html
    restart: always
    container_name: funclub-dev-laravel
    expose:
      - "9000"

  funclub-dev-supervisord:
    image: funclub-dev-laravel:latest
    container_name: funclub-dev-supervisord
    restart: always
    volumes:
      - .:/var/www/html
    user: root
    command: ["/usr/bin/supervisord"]
