version: "3"

services:
  funclub-dev-nginx:
    image: funclub-dev-nginx:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
      dockerfile: ./docker/nginx/Dockerfile
    container_name: funclub-dev-nginx
    restart: always
    volumes:
      - .:/var/www/html:ro
    ports:
      - "9090:80"
    networks:
      backend:
    depends_on:
      - funclub-dev-laravel

  funclub-dev-laravel:
    image: funclub-dev-laravel:latest
    build:
      context: .
      args:
        - "BUILD_ARGUMENT_ENV=dev"
      dockerfile: ./Dockerfile
    volumes:
      - .:/var/www/html
    restart: always
    container_name: funclub-dev-laravel
    networks:
      backend:
    expose:
      - "9000"

  funclub-dev-supervisord:
    image: funclub-dev-laravel:latest
    container_name: funclub-dev-supervisord
    restart: always
    volumes:
      - .:/var/www/html
    user: root
    networks:
      backend:
    command:
      ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

  funclub-mysql:
    image: mysql:5.7
    container_name: funclub-mysql
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dev-funclub
    volumes:
      - funclub_mysql_data:/var/lib/mysql
    networks:
      backend:

networks:
  backend:
volumes:
  funclub_mysql_data: {}
